import { TranslationStrings, Review } from './types';

export const GOOGLE_SHEET_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTnuBv3c1pjg9GuxlZ5AfuMQMn1FCnh9z7kiR011KXQtGbR5AzAqwaE5iAAIbHzP3ezSoQYUlks1oiy/pub?gid=0&single=true&output=csv";
export const REVIEWS_API_URL = "";

export const THEME = {
  primary: "#1a1a1a",
  accent: "#8b7355",
  background: "#ffffff",
  textDark: "#1a1a1a",
};

export const MOCK_REVIEWS: Review[] = [
  { id: '1', author: 'Valentina P.', rating: 5, comment: 'El mejor café de Palermo. El ambiente es súper tranquilo y la atención de diez.', date: '2024-03-10', isVerified: true },
  { id: '2', author: 'Mark S.', rating: 4, comment: 'Excellent family blend. Very authentic and cozy.', date: '2024-03-08', isVerified: true },
  { id: '3', author: 'Julián G.', rating: 5, comment: 'Un clásico de Cerviño. Siempre vuelvo por el avocado toast.', date: '2024-03-05', itemName: 'AVOCADO TOAST', isVerified: true },
];

export const TRANSLATIONS: Record<'en' | 'es', TranslationStrings> = {
  en: {
    landingTitle: "ROTONDO CAFÉ",
    selectLanguage: "SELECT LANGUAGE",
    categories: "OUR MENU",
    backToMenu: "BACK TO MENU",
    backToHome: "HOME",
    reviews: "Reviews",
    currency: "$",
    available: "Available",
    unavailable: "OUT OF STOCK",
    navHome: "HOME",
    navAbout: "ABOUT",
    navBranches: "LOCATION",
    navMenu: "MENU",
    navContact: "SOCIAL",
    heroTitle: "ROTONDO",
    heroSubtitle: "FAMILY BLEND | EST. PALERMO",
    seeMenu: "VIEW MENU",
    aboutTitle: "OUR TRADITION",
    aboutText: "Rotondo Café is a family heritage project. We focus on the essence of the 'Family Blend', selecting the best coffee beans to create a unique and cozy experience in the heart of Palermo.",
    branchesTitle: "FIND US",
    branchPalermo: "CAFÉ ROTONDO",
    branchPalermoAddress: "Boulevard Cerviño 3907, Palermo.",
    branchRecoleta: "ROTONDO",
    branchRecoletaAddress: "Buenos Aires, Argentina",
    hoursTitle: "OPENING HOURS",
    hoursValue: "MON to MON 8.00 to 20.00",
    contactTitle: "FOLLOW OUR STORY",
    contactText: "Visit us at Palermo or stay connected through our social media for daily updates and specials.",
    followUs: "FOLLOW US",
    ingredients: "Ingredients",
    sides: "With",
    specials: "SPECIALS",
    orderSummary: "Order",
    emptyCart: "Empty",
    total: "Total",
    checkout: "Checkout",
    continueOrdering: "Back",
  },
  es: {
    landingTitle: "ROTONDO CAFÉ",
    selectLanguage: "SELECCIONAR IDIOMA",
    categories: "NUESTRO MENÚ",
    backToMenu: "VOLVER AL MENÚ",
    backToHome: "INICIO",
    reviews: "Reseñas",
    currency: "$",
    available: "Disponible",
    unavailable: "AGOTADO",
    navHome: "INICIO",
    navAbout: "NOSOTROS",
    navBranches: "UBICACIÓN",
    navMenu: "MENÚ",
    navContact: "CONTACTO",
    heroTitle: "ROTONDO",
    heroSubtitle: "FAMILY BLEND | PALERMO",
    seeMenu: "VER MENÚ",
    aboutTitle: "NUESTRA TRADICIÓN",
    aboutText: "Rotondo Café es un proyecto de herencia familiar. Nos enfocamos en la esencia del 'Family Blend', seleccionando los mejores granos para crear una experiencia única y acogedora en el corazón de Palermo.",
    branchesTitle: "DONDE ESTAMOS",
    branchPalermo: "CAFÉ ROTONDO",
    branchPalermoAddress: "Boulevard Cerviño 3907, Palermo.",
    branchRecoleta: "ROTONDO",
    branchRecoletaAddress: "Buenos Aires, Argentina",
    hoursTitle: "HORARIOS",
    hoursValue: "LUN a LUN de 8.00 to 20.00",
    contactTitle: "SEGUÍ NUESTRA HISTORIA",
    contactText: "Vení a visitarnos a Palermo o mantenete conectado a través de nuestras redes para novedades y especiales del día.",
    followUs: "SEGUINOS",
    ingredients: "Ingredientes",
    sides: "Con",
    specials: "ESPECIALES",
    orderSummary: "Pedido",
    emptyCart: "Sin items",
    total: "Total",
    checkout: "Finalizar",
    continueOrdering: "Volver",
  },
};